// src/pages/peptide/order/index.jsx
// 多肽订单
import {
  Button,
  Card,
  Col,
  DatePicker,
  Form,
  Icon,
  Input,
  Row,
  Select,
} from 'antd';
import React, { Component } from 'react';
import { PageHeaderWrapper } from '@ant-design/pro-layout';
import StandardTable from '@/components/StandardTable';
import { connect } from 'dva';
import { formatter } from '@/utils/utils';
import api from '@/api';
import OrderMask from '@/pages/peptide/components/order-mask';
import CustomerMask from '@/pages/peptide/components/customer-mask';
import SubCustomerMask from '@/pages/peptide/components/subCustomer-mask';
import ContactMask from '@/pages/peptide/components/contact-mask';
import SalerMask from '@/pages/peptide/components/saler-mask';

const EditableContext = React.createContext();
const FormItem = Form.Item;
const { Option } = Select;
const { RangePicker } = DatePicker;
const { Search } = Input;


@Form.create()
@connect(({ peptide }) => ({
  peptide,
}))
class SearchPage extends Component {
  constructor(props) {
    super(props);
    this.state = {
      expandForm: false,
    }
  }

  componentDidMount() {
    this.submit();
  }

  submit = e => {
    if (e) e.preventDefault();
    const val = this.props.form.getFieldsValue();
    this.props.getTableData({ page: 1, ...val });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  }

  toggleForm = () => {
    const { expandForm } = this.state;
    this.setState({
      expandForm: !expandForm,
    });
  };

  getMaskData = (v, type) => {
    if (type === 'customer') {
      this.props.form.setFieldsValue({
        customerCode: v.code,
      });
    }
    if (type === 'subCustomer') {
      this.props.form.setFieldsValue({
        subCustomerCode: v.code,
      });
    }
    if (type === 'contact') {
      this.props.form.setFieldsValue({
        contactCode: v.code,
      });
    }
    if (type === 'saler') {
      this.props.form.setFieldsValue({
        salerCode: v.code,
      });
    }
  }

  renderAdvancedForm() {
    const {
      form: { getFieldDecorator },
      peptide: {
        regions,
        offices,
        currencys,
        commonData,
      },
    } = this.props;
    return (
      <Form onSubmit={this.submit} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
        <Col lg={6} md={8} sm={12}>
            <FormItem label="订单编号">
              {getFieldDecorator('code')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="客户">
              {getFieldDecorator('customerCode')(<Search onSearch={() => this.showCustomer.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="负责人">
            {getFieldDecorator('subCustomerCode')(<Search onSearch={() => this.showSubCustomer.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="订货人">
            {getFieldDecorator('contactCode')(<Search onSearch={() => this.showContact.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售员">
            {getFieldDecorator('salerCode')(<Search onSearch={() => this.showSaler.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="币种">
              {getFieldDecorator('currency', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {currencys.map(item =>
                 <Option key={item.code} value={item.code}>{`${item.code}-${item.name}`}</Option>,
               )}
                </Select>,
              )}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售网点">
              {getFieldDecorator('officeCode', { initialValue: '' })(
               <Select>
               <Option value="">全部</Option>
               {offices.map(item =>
                 <Option key={item.code} value={item.code}>{`${item.code}-${item.name}`}</Option>,
               )}
               </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售大区">
              {getFieldDecorator('regionCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {regions.map(item =>
                    <Option key={item.code} value={item.code}>{`${item.code}-${item.name}`}</Option>,
                  )}
                  </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售组织">
              {getFieldDecorator('rangeOrganization', { initialValue: '' })(
                <Select>
                  {commonData.rangeOrganization.map(item =>
                    <Option key={item.id} value={item.id}>{item.name}</Option>,
                  )}
                  </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售渠道">
              {getFieldDecorator('rangeChannel', { initialValue: '' })(
                <Select>
                 {commonData.rangeChannel.map(item =>
                    <Option key={item.id} value={item.id}>{item.name}</Option>,
                  )}
                  </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="创建日期">
              {getFieldDecorator('wanchengshijian')(
                <RangePicker />,
              )}
            </FormItem>
          </Col>
        </Row>
        <div style={{ overflow: 'hidden' }}>
          <div style={{ float: 'right', marginBottom: 24 }}>
            <Button type="primary" htmlType="submit">
              查询
            </Button>
            <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
              重置
            </Button>
            <a style={{ marginLeft: 8 }} onClick={this.toggleForm}>
              收起 <Icon type="up" />
            </a>
          </div>
        </div>
      </Form>
    );
  }

  renderSimpleForm() {
    const { form } = this.props;
    const { getFieldDecorator } = form;
    return (
      <Form onSubmit={this.submit} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="订单编号">
              {getFieldDecorator('code')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="客户">
              {getFieldDecorator('customerCode')(<Search onSearch={() => this.showCustomer.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="负责人">
            {getFieldDecorator('subCustomerCode')(<Search onSearch={() => this.showSubCustomer.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="订货人">
            {getFieldDecorator('contactCode')(<Search onSearch={() => this.showContact.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售员">
            {getFieldDecorator('salerCode')(<Search onSearch={() => this.showSaler.visibleShow(true)} />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <span className="submitButtons">
              <Button type="primary" htmlType="submit">
                查询
              </Button>
              <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
                重置
              </Button>
              <a style={{ marginLeft: 8 }} onClick={this.toggleForm}>
                展开 <Icon type="down" />
              </a>
            </span>
          </Col>
        </Row>
      </Form>
    );
  }

  // 渲染表单
  renderForm = () => {
    const { expandForm } = this.state;
    return expandForm ? this.renderAdvancedForm() : this.renderSimpleForm();
  }

  render() {
    return (
      <div className="tableListForm">
      {this.renderForm()}
      <CustomerMask
        onRef={ref => { this.showCustomer = ref }}
        getData={v => this.getMaskData(v, 'customer')}
        />
      <SubCustomerMask
        onRef={ref => { this.showSubCustomer = ref }}
        getData={v => this.getMaskData(v, 'subCustomer')}
      />
      <ContactMask
        onRef={ref => { this.showContact = ref }}
        getData={v => this.getMaskData(v, 'contact')}
      />
      <SalerMask
        onRef={ref => { this.showSaler = ref }}
        getData={v => this.getMaskData(v, 'saler')}
      />
      </div>
    );
  }
}

/**
 * 表格编辑组件
 */
class EditableCell extends React.Component {
  renderCell = ({ getFieldDecorator }) => {
    const {
      editing,
      dataIndex,
      title,
      inputType,
      record,
      index,
      children,
      rules,
      ...restProps
    } = this.props;
    return (
      <td {...restProps}>
        {editing ? (
          <Form.Item>
            {getFieldDecorator(dataIndex, {
              rules,
              initialValue: record[dataIndex],
            })(inputType)}
          </Form.Item>
        ) : (
          children
        )}
      </td>
    );
  };

  render() {
    return <EditableContext.Consumer>{this.renderCell}</EditableContext.Consumer>;
  }
}

@connect(({ peptide }) => ({
  peptide,
}))
class Order extends Component {
  constructor(props) {
    super(props);
    this.state = {
      formValues: {
        page: 1,
        rows: 10,
      },
      list: [],
      total: 0,
      loading: false,
      selectedRows: [],
      editIndex: -1,
      regions: [], // 销售大区
      offices: [], // 销售网点
      invtypes: [], // 开票方式
      payMethods: [], // 付款方式
      payTerms: [], // 付款条件
      currencys: [], // 货币类型
    }
  }

  componentDidMount() {
    const { dispatch } = this.props;
    dispatch({
      type: 'peptide/getRegions', // 销售大区
    })
    dispatch({
      type: 'peptide/getOffices', // 销售网点
    })
    dispatch({
      type: 'peptide/getInvtypes', // 开票方式
    })
    dispatch({
      type: 'peptide/getPaymethods', // 付款方式
    })
    dispatch({
      type: 'peptide/getPayterms', // 付款条件
    })
    dispatch({
      type: 'peptide/getCurrencys', // 货币类型
    })
  }

  componentWillReceiveProps(nextProps) {
    const { peptide:
      { regions, offices, invtypes, payMethods, payTerms, currencys },
     } = nextProps
    if (nextProps) {
      this.setState({
        regions,
        offices,
        invtypes,
        payMethods,
        payTerms,
        currencys,
      });
    }
  }

  handleStandardTableChange = pagination => {
    this.getTableData({
      page: pagination.current,
      rows: pagination.pageSize,
    });
  }

  handleSelectRows = rows => {
    this.setState({
      selectedRows: rows,
    });
  };

  // 获取表格数据
  getTableData = (options = {}) => {
    const { formValues } = this.state;
    const query = Object.assign({}, formValues, options);
    this.setState({
      formValues: query,
      loading: true,
    });

    api.peptideorder.getOrder(query).then(res => {
      this.setState({
        list: res.rows,
        total: res.total,
        loading: false,
        editIndex: -1,
      });
    });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  };

  toggleForm = () => {
    const { expandForm } = this.state;
    this.setState({
      expandForm: !expandForm,
    });
  };

  renderForm = () => {
    const { expandForm } = this.state;
    return expandForm ? this.renderAdvancedForm() : this.renderSimpleForm();
  };

  // 作废数据
  // deleteRow = row => {
  //   api.carrier.cancelCarrier(row.id).then(() => {
  //     this.getTableData();
  //   });
  // };

  render() {
    const {
      formValues: { page: current, rows: pageSize },
      selectedRows,
      list,
      total,
      loading,
      regions,
      offices,
      invtypes,
      payMethods,
      payTerms,
      currencys,
    } = this.state;
    const { peptide: { commonData } } = this.props
    const data = { list, pagination: { current, pageSize, total } };
    let tableWidth = 0;

    let columns = [
      {
        title: '编号',
        dataIndex: 'code',
        width: 100,
      },
      {
        title: '状态',
        dataIndex: 'status',
        width: 100,
        render(text) {
          return formatter(commonData.orderStatus, text);
        },
      },
      {
        title: '客户',
        dataIndex: 'customerName',
        width: 200,
      },
      {
        title: '负责人',
        dataIndex: 'subCustomerName',
        width: 200,
      },
      {
        title: '订货人',
        dataIndex: 'contactName',
        width: 100,
      },
      {
        title: '备注',
        dataIndex: 'remark',
        width: 200,
      },
      {
        title: '订货人手机',
        dataIndex: 'contactMobile',
        width: 100,
      },
      {
        title: '订货人邮箱',
        dataIndex: 'contactEmail',
        width: 100,
      },
      {
        title: '销售组织',
        dataIndex: 'rangeOrganization',
        width: 100,
        render(text) {
          return formatter(commonData.rangeOrganization, text);
        },
      },
      {
        title: '分销渠道',
        dataIndex: 'rangeChannel',
        width: 100,
        render(text) {
          return formatter(commonData.rangeChannel, text);
        },
      },
      {
        title: '销售大区',
        dataIndex: 'regionCode',
        width: 150,
        render(text) {
          return `${text} - ${formatter(regions, text, 'code', 'name')}`;
        },
      },
      {
        title: '销售网点',
        dataIndex: 'officeCode',
        width: 150,
        render(text) {
          return `${text} - ${formatter(offices, text, 'code', 'name')}`;
        },
      },
      {
        title: '交货方式',
        dataIndex: 'deliveryType',
        width: 100,
        render(text) {
          return formatter(commonData.deliveryTypeStatus, text);
        },
      },
      {
        title: '开票方式',
        dataIndex: 'invoiceType',
        width: 150,
        render(text) {
          return formatter(invtypes, text, 'code', 'name');
        },
      },
      {
        title: '付款方式',
        dataIndex: 'paymentMethod',
        width: 100,
        render(text) {
          return formatter(payMethods, text, 'code', 'name');
        },
      },
      {
        title: '付款条件',
        dataIndex: 'paymentTerm',
        width: 250,
        render(text) {
          return `${text} - ${formatter(payTerms, text, 'code', 'name')}`;
        },
      },
      {
        title: 'SAP销售订单号',
        dataIndex: 'sapOrderCode',
        width: 140,
      },
      {
        title: 'SAP交货单号',
        dataIndex: 'sapDeliveryCode',
        width: 140,
      },
      {
        title: '运费',
        dataIndex: 'freight',
        width: 100,
      },
      {
        title: '订单金额',
        dataIndex: 'amount',
        width: 100,
      },
      {
        title: '币种',
        dataIndex: 'currency',
        width: 100,
        render(text) {
          return formatter(currencys.code, text);
        },
      },
      {
        title: '随货开票',
        dataIndex: 'invoiceByGoods',
        width: 100,
        render(text) { return text ? '是' : '否' },
      },
      {
        title: '送货地址',
        dataIndex: 'address',
        width: 500,
      },
      {
        title: '创建人姓名',
        dataIndex: 'creatorName',
        width: 120,
      },
      {
        title: '创建时间',
        dataIndex: 'createDate',
        width: 100,
      },
      {
        title: '修改人姓名',
        dataIndex: 'changerName',
        width: 120,
      },
      {
        title: '修改时间',
        dataIndex: 'changeDate',
        width: 100,
      },
      {
        title: '发货人姓名',
        dataIndex: 'sendName',
        width: 120,
      },
      {
        title: '发货时间',
        dataIndex: 'sendDate',
        width: 100,
      },
      {
        title: '作废人姓名',
        dataIndex: 'cancelName',
        width: 120,
      },
      {
        title: '作废时间',
        dataIndex: 'cancelDate',
        width: 100,
      },
      {
        title: '审核人姓名',
        dataIndex: 'checkName',
        width: 120,
      },
      {
        title: '审核时间',
        dataIndex: 'checkDate',
        width: 100,
      },
      {
        title: '完成人姓名',
        dataIndex: 'finishName',
        width: 120,
      },
      {
        title: '完成时间',
        dataIndex: 'finishDate',
        width: 100,
      },
      // {
      //   fixed: 'right',
      //   title: '操作',
      //   width: 100,
      //   render: (value, row, index) => {
      //     const { editIndex } = this.state;
      //     let actions;
      //     if (editIndex !== index) {
      //       if (row.status === 1) {
      //         actions = (
      //           <>
      //             <a>删除</a>
      //           </>
      //         );
      //       } else {
      //         actions = (
      //           <>
      //             <a>恢复</a>
      //           </>
      //         );
      //       }
      //     }
      //     if (editIndex === index) {
      //       actions = (
      //         <>
      //           <a>保存</a>
      //           <Divider type="vertical" />
      //           <a>退出</a>
      //         </>
      //       );
      //     }
      //     return actions;
      //   },
      // },
    ];

    columns = columns.map(col => {
      // eslint-disable-next-line no-param-reassign
      if (!col.width) col.width = 100;
      tableWidth += col.width;
      if (!col.editable) {
        return col;
      }
      return {
        ...col,
        onCell: (record, rowIndex) => ({
          record,
          rules: col.rules,
          inputType: col.inputType,
          dataIndex: col.dataIndex,
          title: col.title,
          editing: rowIndex === this.state.editIndex,
        }),
      };
    });

    const components = {
      body: {
        cell: EditableCell,
      },
    };
    return (
      <PageHeaderWrapper>
        <Card bordered={false}>
          <div className="tableList">
            <SearchPage getTableData={this.getTableData} />
            <div className="tableListOperator">
              <Button icon="plus" type="primary" onClick={ () => { this.showOrder.visibleShow(true) }}>
                新建
              </Button>
            </div>
            <EditableContext.Provider value={this.props.form}>
              <StandardTable
                scroll={{ x: tableWidth }}
                rowClassName="editable-row"
                components={components}
                selectedRows={selectedRows}
                loading={loading}
                data={data}
                columns={columns}
                onSelectRow={this.handleSelectRows}
                onChange={this.handleStandardTableChange}
              />
            </EditableContext.Provider>
          </div>
        </Card>
        <OrderMask
          onRef={ref => { this.showOrder = ref }}
        />
      </PageHeaderWrapper>
    );
  }
}

export default Form.create()(Order);

// src/views/seq/order.vue
<!-- 测序订单 -->
<template>
  <div class="page-content">

    <div class="table-search">
      <a-form layout="inline" :form="form" @submit.prevent="handleSearch">
        <a-row :gutter="24">
          <a-col :md="6" :xl="4">
            <a-form-item label="编号">
              <a-input v-decorator="['code']"/>
            </a-form-item>
          </a-col>
          <a-col :md="6" :xl="4">
            <a-form-item label="名称">
              <a-input v-decorator="['name']"/>
            </a-form-item>
          </a-col>
          <a-col :md="6" :xl="4">
            <a-form-item label="别名">
              <a-input v-decorator="['alias']"/>
            </a-form-item>
          </a-col>
          <a-col :md="6" :xl="4">
            <a-form-item label="系列">
              <a-select v-decorator="['seriesId', {initialValue: ''}]">
                <a-select-option value="">全部</a-select-option>
                <a-select-option v-for="series in $store.state.seq.series" :value="series.id" :key="series.id">{{ series.name }}</a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
          <a-col :md="6" :xl="4">
            <a-form-item label="状态">
              <a-select v-decorator="['status', {initialValue: 1}]">
                <a-select-option value="">全部</a-select-option>
                <a-select-option v-for="status in $store.state.basic.status" :value="status.id" :key="status.id">{{ status.name }}</a-select-option>
              </a-select>
            </a-form-item>
          </a-col>
        </a-row>
        <a-button type="primary" icon="search" html-type="submit" style="display:none;">查询</a-button>
      </a-form>
    </div>

    <div class="table-operator">
      <a-button-group>
        <a-button icon="search" @click="handleSearch">查询</a-button>
        <a-button icon="plus" type="primary">新建</a-button>
      </a-button-group>
    </div>

    <vxe-grid
      highlight-hover-row
      auto-resize
      height="600"
      ref="orderTable"
      :loading="orderTable.loading"
      :columns="orderTable.columns"
      :pager-config="orderTable.pagerConfig"
      :data.sync="orderTable.tableData"
      @page-change="({pageSize, currentPage}) => this.$utils.tablePageChange({pageSize, currentPage, table: orderTable, callback: handleSearch})">
    </vxe-grid>
  </div>
</template>

<script>
export default {
  name: 'SeqOrder',
  components: {
  },
  data () {
    return {
      form: this.$form.createForm(this),
      queryParam: {},
      orderTable: {
        id: 0,
        xTable: null,
        loading: false,
        tableData: [],
        columns: [],
        pagerConfig: {
          currentPage: 1,
          pageSize: 10,
          total: 0
        }
      }
    };
  },
  mounted () {
    this.setColumn();
    this.handleSearch();
  },
  methods: {
    // 设置表格列属性
    setColumn () {
      const tableName = 'orderTable';
      // const { formatter } = this.$utils;
      // const { basic, seq } = this.$store.state;

      const columns = [
        { type: 'radio', width: 40 },
        { type: 'index', width: 40 },
        { title: '订单编号', field: 'code' },
        { title: '状态', field: 'status' },
        { title: '备注', field: 'remark' },
        { title: '客户', field: 'customerName' },
        { title: '负责人', field: 'subcustomerName' },
        { title: '订货人', field: 'contactName' },
        { title: '订货人邮箱', field: 'contactEmail' },
        { title: '订货人手机', field: 'contactMobile' },
        { title: '创建人姓名', field: 'creatorName' },
        { title: '创建时间', field: 'createDate' },
        { title: '审核人姓名', field: 'checkName' },
        { title: '审核时间', field: 'checkDate' },
        { title: '产品金额', field: 'productAmount' },
        { title: '订单金额', field: 'amount' },
        { title: '销售员', field: 'salerName' },
        { title: '修改人姓名', field: 'changerName' },
        { title: '修改时间', field: 'changeDate' },
        { title: '来源单号', field: 'sourceCode' },
        { title: '运费', field: 'freight' },
        { title: '是否拼接', field: 'isSplice' },
        { title: '样品返还', field: 'sampleReturn' },
        { title: '币种', field: 'currency' },
        { title: '订单类型', field: 'orderType' },
        { title: '测序点', field: 'seqfactoryId' },
        { title: '测序中心', field: 'factory' },
        { title: '销售组织', field: 'rangeOrganization' },
        { title: '分销渠道', field: 'rangeChannel' },
        { title: '销售大区', field: 'regionCode' },
        { title: '销售网点', field: 'officeCode' },
        { title: '开票方式', field: 'invoiceType' },
        { title: '付款方式', field: 'paymentMethod' },
        { title: '付款条件', field: 'paymentTerm' },
        { title: '随货开票', field: 'invoiceByGoods' },
        { title: 'SAP销售订单号', field: 'sapOrderCode' },
        { title: 'SAP交货单号', field: 'sapDeliveryCode' },
        { title: '交货方式', field: 'deliveryType' },
        { title: '仓库', field: 'storageCode' },
        { title: '客户订单号', field: 'customerPocode' },
        { title: '是否有明细', field: 'isDetails' },
        { title: '收样网点', field: 'sampleOfficeCode' },
        { title: '送货地址', field: 'address' },
        { title: '作废人姓名', field: 'cancelName' },
        { title: '作废时间', field: 'cancelDate' },
        { title: '完成时间', field: 'finishDate' },
        { title: '完成人姓名', field: 'finishName' }
      ];

      columns.forEach(function (e) {
        if (!e.width) e.width = 100;
      });

      this[tableName].columns = columns;
      this[tableName].xTable = this.$refs[tableName].$refs.xTable;
    },
    // 查询
    handleSearch () {
      const tableName = 'orderTable';
      this[tableName].loading = true;
      const { currentPage, pageSize } = this[tableName].pagerConfig;

      const queryParam = this.form.getFieldsValue();
      const params = Object.assign({ page: currentPage, rows: pageSize }, queryParam);

      this.$api.seqorder.getOrderList(params, true).then((data) => {
        this[tableName].tableData = data.rows;
        this[tableName].pagerConfig.total = data.total;
        this[tableName].pagerConfig.currentPage = params.page;
        this[tableName].pagerConfig.pageSize = params.rows;
      }).finally(() => {
        this[tableName].loading = false;
      });
    }
  }
};
</script>

<style lang="scss" scoped>

</style>
