// src/views/system/group.vue
<template>
  <div class="page-content">
    <div class="table-search">
      <a-form layout="inline" :form="form" @submit="handleSearch">
        <a-row :gutter="2">
          <a-col :xxl="4" :xl="6" :md="8" :sm="24">
            <a-form-item label="分组名称">
              <a-input v-decorator="['name']"/>
            </a-form-item>
          </a-col>
        </a-row>
        <a-button type="primary" icon="search" html-type="submit" style="display:none;">查询</a-button>
      </a-form>
    </div>
    <div>
      <a-row :gutter="0">
        <a-col :span="6">
          <a-card title="分组">
            <div class="table-operator">
              <a-button-group>
                <a-button type="primary" size="small" icon="search" @click="handleSearch">查询</a-button>
                <a-button type="primary" size="small" icon="plus">新建</a-button>
                <a-button type="primary" size="small" icon="delete">删除</a-button>
                <a-button type="primary" size="small" icon="save">保存</a-button>
              </a-button-group>
            </div>

            <s-table
              size="small"
              :scroll="{ x: 300, y: 400 }"
              :columns="columns"
              :data="loadData"
              :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
            >
            </s-table>
          </a-card>
        </a-col>
        <a-col :span="18">
          <a-card title="规则分组">
            <div class="table-operator">
              <a-button-group>
                <a-button type="primary" size="small" icon="search" @click="handleSearch">查询</a-button>
                <a-button type="primary" size="small" icon="plus">新建</a-button>
                <a-button type="primary" size="small" icon="delete">删除</a-button>
                <a-button type="primary" size="small" icon="save">保存</a-button>
              </a-button-group>
            </div>

            <s-table
              ref="table"
              size="small"
              bordered
              :scroll="{ x: 500, y: 400 }"
              :columns="rulegroupcolumns"
              :data="loadData"
              :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
            >
            </s-table>
          </a-card>
        </a-col>
      </a-row>
    </div>
  </div>
</template>

<script>
import STable from '@/components/Table';

export default {
  name: 'SystemUser',
  components: {
    STable
  },
  data () {
    return {
      form: this.$form.createForm(this),
      advanced: true,
      columns: [
        { title: '分组名称', dataIndex: 'name' }
      ],
      rulegroupcolumns: [
        { title: '名称', dataIndex: '' },
        { title: 'Client', dataIndex: 'sourceClient' },
        { title: 'Type', dataIndex: 'sourceType' },
        { title: '资源', dataIndex: 'sourcePath' },
        { title: '资源描述', dataIndex: 'sourceDesc' },
        { title: '参数类型', dataIndex: 'paramType' },
        { title: '参数', dataIndex: 'parameterField' },
        { title: '参数描述', dataIndex: 'parameterDesc' },
        { title: 'OP', dataIndex: 'op' },
        { title: '值', dataIndex: 'value' },
        { title: '状态', dataIndex: 'status' }
      ],
      queryParam: {},
      loadData: parameter => {
        const params = Object.assign(parameter, this.queryParam);
        return this.$api.system.getGroupsList(params).then(res => {
          return {
            data: res.rows,
            page: params.page,
            total: res.total
          };
        });
      },
      selectedRowKeys: [],
      selectedRows: []
    };
  },
  mounted () {},
  methods: {
    onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys;
      this.selectedRows = selectedRows;
      const params = selectedRowKeys[0];
      this.$api.system.getAuthorityList(params).then(res => {
        console.log(res.rows);
      });
    },
    toggleAdvanced () {
      this.advanced = !this.advanced;
    },
    handleSearch () {
      this.$refs.table.refresh(true);
    }
  }
};
</script>

<style>
#components-button-demo-button-group h4 {
  margin: 16px 0;
  font-size: 14px;
  line-height: 1;
  font-weight: normal;
}
#components-button-demo-button-group h4:first-child {
  margin-top: 0;
}
#components-button-demo-button-group .ant-btn-group {
  margin-right: 8px;
}
</style>

// src/pages/system/group/components/Group.jsx
import {
  Button,
  Card,
  Col,
  Form,
  Input,
  Row,
  Select,
  Divider,
} from 'antd';
import React, { Component } from 'react';
import StandardTable from '@/components/StandardTable';
import api from '@/api';

const FormItem = Form.Item;
// const { Option } = Select;
// const { Search } = Input;

const gridStyle = {
  width: '35%',
  textAlign: 'center',
};
const onGridStyle = {
  width: '100%',
  textAlign: 'center',
};

class Group extends Component {
  state = {
    pagination: {
      current: 1,
      pageSize: 10,
      total: 0,
    },
    list: [],
    loading: false,
    selectedRows: [],
  }

  // 设置列 分组
  columns = [
    {
      title: '分组名称',
      dataIndex: 'name',
      width: 300,
    },
    {
      fixed: 'right',
      title: '操作',
      width: 120,
      render: (value, row, index) => {
        // const { status } = row;
        const { editIndex } = this.state;
        let actions;
        if (editIndex !== index) {
          actions = (
            <>
              <a>删除</a>
            </>
          );
        }
        if (editIndex === index) {
          actions = (
            <>
              <a>保存</a>
              <Divider type="vertical" />
              <a>退出</a>
            </>
          );
        }
        return actions;
      },
    },
  ];

  componentDidMount() {
    this.getTableData();
  }

  handleSearch = e => {
    e.preventDefault();
    this.getTableData({ page: 1 });
  }

  handleStandardTableChange = (pagination, filtersArg, sorter) => {
    this.getTableData({
      page: pagination.current,
      rows: pagination.pageSize,
    });
  }

  handleSelectRows = rows => {
    this.setState({
        selectedRows: rows,
    });
  }

  handleSearchGroupRules = data => {
    // this.context.value = data.id;
  }

  // 获取表格数据 分组
  getTableData = (options = {}) => {
    this.setState({
        loading: true,
    });
    const { form } = this.props;
    const { pagination: { current: page, pageSize: rows } } = this.state;
    const query = Object.assign(form.getFieldsValue(), { page, rows }, options);

    api.system.getGroups(query, true).then(data => {
      this.setState({
        loading: false,
        list: data.rows,
        pagination: {
          total: data.total,
          current: query.page,
          pageSize: query.rows,
        },
      });
    });
  }

  // 新增
  handleAdd = () => {
    console.log('add');
  }

  // 渲染表单
  renderForm = () => this.renderAdvancedForm()

  // 显示搜索
  renderAdvancedForm() {
    const {
      form: { getFieldDecorator },
    } = this.props;
    return (
      <Form onSubmit={this.handleSearch} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="分组名称">
              {getFieldDecorator('name')(<Input />)}
            </FormItem>
          </Col>
        </Row>
        <div style={{ overflow: 'hidden' }}>
          <div style={{ float: 'right', marginBottom: 24 }}>
            <Button type="primary" htmlType="submit">
              查询
            </Button>
            <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
              重置
            </Button>
          </div>
        </div>
      </Form>
    );
  }

  render() {
    const { list, pagination, loading, selectedRows } = this.state;
    const data = { list, pagination };

    return (
      <>
        <Card.Grid style={onGridStyle} hoverable={false}>
        <div className="tableListForm">{this.renderForm()}</div>
        </Card.Grid>
        <Card.Grid style={gridStyle} bordered="false" hoverable={false}>
          <div className="tableList">
            <StandardTable
              scroll={{ x: 400 }}
              selectedRows={selectedRows}
              loading={loading}
              data={data}
              columns={this.columns}
              onSelectRow={this.handleSelectRows}
              onChange={this.handleStandardTableChange}
              onRowClick={
                record => {
                  this.handleSearchGroupRules(record);
                }
              }
            />
          </div>
        </Card.Grid>
      </>
    );
  }
}

export default Form.create()(Group);
