// src/pages/peptide/components/amino-acid-mask.jsx
// 氨基酸弹框
import {
  Button,
  Col,
  Divider,
  Form,
  Input,
  Row,
  Select,
  Table,
  Modal,
} from 'antd';
import React, { Component, Fragment } from 'react';

import api from '@/api';
import './style.less'
import { connect } from 'dva';

const FormItem = Form.Item;
const { Option } = Select;

/**
 * 页面顶部筛选表单
 */
@Form.create()
class Search extends Component {
  componentDidMount() {
    this.submit();
  }

  submit = e => {
    if (e) e.preventDefault();
    const val = this.props.form.getFieldsValue();
    this.props.getTableData({ page: 1, ...val });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  }

  // 渲染表单
  renderForm = () => {
    const {
      form: { getFieldDecorator },
      status,
    } = this.props;
    return (
      <Form onSubmit={this.submit} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="编号">
              {getFieldDecorator('code')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="名称">
              {getFieldDecorator('name')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="代码">
            {getFieldDecorator('aminoAcidCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="状态">
            {getFieldDecorator('status', { initialValue: 1 })(
                <Select>
                    {status.map(item =>
                      <Option key={item.id} value={item.id}>{item.name}</Option>,
                    )}
                  </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <span className="submitButtons">
              <Button type="primary" htmlType="submit">
                查询
              </Button>
              <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
                重置
              </Button>
            </span>
          </Col>
        </Row>
      </Form>
    );
  }

  render() {
    return (
      <div className="tableListForm">{this.renderForm()}</div>
    );
  }
}

@connect(({ peptide }) => ({
  peptide,
}))
class Order extends Component {
  state = {
    formValues: {
      page: 1,
      rows: 10,
    },
    list: [],
    total: 0,
    loading: false,
    visible: false, // 遮罩层的判断
    data: [],
  }

  componentDidMount () {
    this.props.onRef(this);
  }

  visibleShow = visible => {
    this.setState({ visible })
  }

  handleOk = () => {
    if (this.state.data.length !== 0) {
      this.props.getData(this.state.data);
      this.handleCancel()
    }
  };

  handleCancel = () => {
    this.setState({
      visible: false,
    });
  };

  // 分页
  handleStandardTableChange = pagination => {
    this.getTableData({
      page: pagination.current,
      rows: pagination.pageSize,
    });
  }

  // 获取表格数据
  getTableData = (options = {}) => {
    const { formValues } = this.state;
    const query = Object.assign({}, formValues, options);

    this.setState({
      formValues: query,
      loading: true,
    });

    api.peptideBase.getAminoAcid(query).then(data => {
      const map = {}; const dest = [];
      for (let i = 0; i < data.rows.length; i++) {
        const ai = data.rows[i];
        if (!map[ai.id]) {
          dest.push({
            id: ai.id,
            code: ai.code,
            name: ai.name,
            hydrophilic: ai.hydrophilic,
            hydrophobic: ai.hydrophobic,
            acidic: ai.acidic,
            alkaline: ai.alkaline,
            isCanDisulfideBond: ai.isCanDisulfideBond,
            molecularWeight: ai.molecularWeight,
            isoelectricPoint: ai.isoelectricPoint,
            carboxylationDissociationConstant: ai.carboxylationDissociationConstant,
            aminoDissociationConstant: ai.aminoDissociationConstant,
            status: ai.status,
            creatorName: ai.creatorName,
            createDate: ai.createDate,
            cancelName: ai.cancelName,
            cancelDate: ai.cancelDate,
            aminoAcidType: ai.aminoAcidType,
            longCode: ai.longCode,
            shortCode: ai.shortCode,
          });
          map[ai.id] = ai;
        } else {
          for (let j = 0; j < dest.length; j++) {
            const dj = dest[j];
            if (dj.id === ai.id) {
              dj.cancelName = dj.cancelName || ai.cancelName ? [dj.cancelName, ai.cancelName] : '';
              dj.cancelDate = dj.cancelDate || ai.cancelDate ? [dj.cancelDate, ai.cancelDate] : '';
              dj.shortCode = dj.shortCode || ai.shortCode ? [dj.shortCode, ai.shortCode] : '';
              // dj.shortCode = (dj.shortCode ? dj.shortCode : '')
              // + (ai.shortCode ? ` | ${ai.shortCode}` : '');
              dj.longCode = dj.longCode || ai.longCode ? [dj.longCode, ai.longCode] : '';
              // dj.longCode = (dj.longCode ? dj.longCode : '')
              // + (ai.longCode ? ` | ${ai.longCode}` : '');
              dj.aminoAcidType = dj.aminoAcidType || ai.aminoAcidType ? [dj.aminoAcidType, ai.aminoAcidType] : '';
              // dj.aminoAcidType = (dj.aminoAcidType ? dj.aminoAcidType : '')
              // + (ai.aminoAcidType ? ` | ${ai.aminoAcidType}` : '');
              break;
            }
          }
        }
      }
      this.setState({
        loading: false,
        list: dest,
        total: dest.length * 2,
      });
    });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  };

  render() {
    const {
      formValues: { page: current, rows: pageSize },
      list,
      total,
      loading,
      visible,
    } = this.state;
    const data = { list, pagination: { current, pageSize, total } };
    const { peptide: { commonData } } = this.props
    let tableWidth = 0;

    let columns = [
      {
        title: '编号',
        dataIndex: 'code',
        width: 100,
      },
      {
        title: '名称',
        dataIndex: 'name',
        width: 100,
      },
      {
        title: '亲水性',
        dataIndex: 'hydrophilic',
        width: 100,
        align: 'center',
        render: text => (text === 1 ? '√' : ''),
      },
      {
        title: '疏水性',
        dataIndex: 'hydrophobic',
        align: 'center',
        width: 100,
        render: text => (text === 1 ? '√' : ''),
      },
      {
        title: '酸性',
        dataIndex: 'acidic',
        align: 'center',
        width: 100,
        render: text => (text === 1 ? '√' : ''),
      },
      {
        title: '碱性',
        dataIndex: 'alkaline',
        align: 'center',
        width: 100,
        render: text => (text === 1 ? '√' : ''),
      },
      {
        title: '是否可做二硫键',
        dataIndex: 'isCanDisulfideBond',
        align: 'center',
        width: 230,
        render: text => (text === 1 ? '√' : ''),
      },
      {
        title: '分子量',
        dataIndex: 'molecularWeight',
        width: 100,
      },
      {
        title: '等电点',
        dataIndex: 'isoelectricPoint',
        width: 100,
      },
      {
        title: '羧基解离常数',
        dataIndex: 'carboxylationDissociationConstant',
        width: 200,
      },
      {
        title: '氨基解离常数',
        dataIndex: 'aminoDissociationConstant',
        width: 200,
      },
      {
        title: '状态',
        dataIndex: 'status',
        width: 100,
        render: text => {
          if (text === 1) return '正常';
          if (text === 2) return '已删除';
          return ''
        },
      },
      {
        title: '创建人',
        dataIndex: 'creatorName',
        width: 100,
      },
      {
        title: '创建时间',
        dataIndex: 'createDate',
        width: 300,
      },
      {
        title: '删除人',
        dataIndex: 'cancelName',
        width: 100,
        render: text => {
          if (!text) return false;
          return (<Fragment>
                    <span>{text[0]}</span>
                    <Divider type="horizontal" style={{ margin: 0 }}/>
                    <span>{text[1]}</span>
                </Fragment>)
        },
      },
      {
        title: '删除时间',
        dataIndex: 'cancelDate',
        width: 300,
        render: text => {
          if (!text) return false;
          return (<Fragment>
                    <span>{text[0]}</span>
                    <Divider type="horizontal" style={{ margin: 0 }}/>
                    <span>{text[1]}</span>
                </Fragment>)
        },
      },
      {
        title: '类型',
        dataIndex: 'aminoAcidType',
        width: 100,
        align: 'center',
        render: text => {
          if (!text) return false;
          return (<Fragment>
                    <span>{text[0]}</span>
                    <Divider type="horizontal" style={{ margin: 0 }}/>
                    <span>{text[1]}</span>
                </Fragment>)
        },
      },
      {
        title: '长代码',
        dataIndex: 'longCode',
        width: 100,
        align: 'center',
        double: true,
        render: text => {
          if (!text) return false;
          return (<Fragment>
                    <span>{text[0]}</span>
                    <Divider type="horizontal" style={{ margin: 0 }}/>
                    <span>{text[1]}</span>
                </Fragment>)
        },
      },
      {
        title: '短代码',
        dataIndex: 'shortCode',
        width: 100,
        align: 'center',
        double: true,
        render: text => {
          if (!text) return false;
          return (<Fragment>
                    <span>{text[0]}</span>
                    <Divider type="horizontal" style={{ margin: 0 }}/>
                    <span>{text[1]}</span>
                </Fragment>)
        },
      },
    ];


    columns = columns.map(col => {
      // eslint-disable-next-line no-param-reassign
      if (!col.width) col.width = 100;
      tableWidth += col.width;
      return col
    });

    const rowSelection = {
      type: 'radio',
      onChange: (selectedRowKeys, selectedRows) => {
          this.setState({
              data: selectedRows[0],
            })
        },
    }

    return (
      <div>
        <Modal
          width="1200px"
          title="多肽氨基酸列表"
          visible={visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
            <Search getTableData={this.getTableData} status={commonData.status}/>
            <div className="tableListOperator">
            </div>
              <Table
                dataSource={data.list}
                columns={columns}
                scroll={{ x: tableWidth, y: 400 }}
                pagination={data.pagination}
                rowKey="code"
                rowSelection={rowSelection}
                loading={loading}
                onChange={this.handleStandardTableChange}
               />
        </Modal>
      </div>
    );
  }
}

export default Form.create()(Order);

// src/components/peptide/amino_acid_mask.vue
<template>
  <div>
    <a-form layout="inline" :form="form" @submit.prevent="handleSearch">
      <a-form-item label="编号">
        <a-input v-decorator="['code']"/>
      </a-form-item>
      <a-form-item label="名称">
        <a-input v-decorator="['name']"/>
      </a-form-item>
      <a-form-item label="状态">
        <a-select v-decorator="['status', {initialValue : 1}]" style="width:100px">
          <a-select-option value="0">全部</a-select-option>
          <a-select-option v-for="item in $store.state.peptide.status" :key="item.id" :value="item.id">{{ item.name }}</a-select-option>
        </a-select>
      </a-form-item>
    </a-form>

    <div class="table-operator">
      <a-button-group>
        <a-button icon="search" @click="handleSearch">查询</a-button>
      </a-button-group>
    </div>

    <vxe-grid
      highlight-hover-row
      auto-resize
      :ref="primerTable.ref"
      :loading="primerTable.loading"
      :columns="primerTable.columns"
      :pager-config="primerTable.pagerConfig"
      :data.sync="primerTable.tableData"
      @cell-click="(options) => handleCellClick(options)"
      @page-change="pagerChange">
    </vxe-grid>
  </div>
</template>

<script>

export default {
  name: 'PeptideAminoAcidMask',
  data () {
    return {
      form: this.$form.createForm(this),
      queryParam: {},
      primerTable: {
        ref: 'primerTable',
        xTable: null,
        loading: false,
        tableData: [],
        columns: [],
        pagerConfig: {
          currentPage: 1,
          pageSize: 10,
          total: 0
        }
      }
    };
  },
  mounted () {
    this.setColumn();
    this.handleSearch();
  },
  methods: {
    setColumn () {
      const tableName = 'primerTable';

      const columns = [
        { type: 'index', width: 40 },
        { title: '编号', field: 'code' },
        { title: '名称', field: 'name' },
        { title: '亲水性',
          field: 'hydrophilic',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '√' : ''; }
        },
        {
          title: '疏水性',
          field: 'hydrophobic',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '√' : ''; }
        },
        {
          title: '酸性',
          field: 'acidic',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '√' : ''; }
        },
        {
          title: '碱性',
          field: 'alkaline',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '√' : ''; }
        },
        {
          title: '是否可做二硫键',
          field: 'isCanDisulfideBond',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '√' : ''; }
        },
        {
          title: '分子量', field: 'molecularWeight', align: 'center'
        },
        {
          title: '等电点', field: 'isoelectricPoint', align: 'center'
        },
        {
          title: '羧基解离常数', field: 'carboxylationDissociationConstant', align: 'center'
        },
        {
          title: '氨基解离常数', field: 'aminoDissociationConstant', align: 'center'
        },
        {
          title: '状态',
          field: 'status',
          align: 'center',
          formatter: function ({ cellValue }) { return cellValue === 1 ? '正常' : '已删除'; }
        },
        {
          title: '创建人', field: 'creatorName', align: 'center'
        },
        {
          title: '创建时间', field: 'createDate', align: 'center'
        },
        { title: '删除人', field: 'cancelName' },
        { title: '删除时间', field: 'cancelDate' },
        { title: '类型', field: 'aminoAcidType', align: 'center' },
        { title: '长代码', field: 'longCode', align: 'center' },
        { title: '短代码', field: 'shortCode', align: 'center' }
      ];

      columns.forEach(function (e) {
        if (!e.width) e.width = 110;
      });

      this[tableName].columns = columns;

      this[tableName].xTable = this.$refs[this[tableName].ref].$refs.xTable;
    },
    handleSearch () {
      const tableName = 'primerTable';
      this[tableName].loading = true;
      const { currentPage, pageSize } = this[tableName].pagerConfig;

      const queryParam = this.form.getFieldsValue();
      const params = Object.assign({ page: currentPage, rows: pageSize }, queryParam);

      this.$api.peptideBase.getAminoAcid(params).then(res => {
        var map = {}; var dest = [];
        for (let i = 0; i < res.rows.length; i++) {
          var ai = res.rows[i];
          if (!map[ai.code]) {
            dest.push({
              id: ai.id,
              code: ai.code,
              name: ai.name,
              hydrophilic: ai.hydrophilic,
              hydrophobic: ai.hydrophobic,
              acidic: ai.acidic,
              alkaline: ai.alkaline,
              isCanDisulfideBond: ai.isCanDisulfideBond,
              molecularWeight: ai.molecularWeight,
              isoelectricPoint: ai.isoelectricPoint,
              carboxylationDissociationConstant: ai.carboxylationDissociationConstant,
              aminoDissociationConstant: ai.aminoDissociationConstant,
              status: ai.status,
              creatorName: ai.creatorName,
              createDate: ai.createDate,
              cancelName: ai.cancelName,
              cancelDate: ai.cancelDate,
              aminoAcidType: ai.aminoAcidType,
              longCode: ai.longCode,
              shortCode: ai.shortCode
            });
            map[ai.code] = ai;
          } else {
            for (let j = 0; j < dest.length; j++) {
              var dj = dest[j];
              if (dj.code === ai.code) {
                dj.shortCode = (dj.shortCode ? dj.shortCode : '') + (ai.shortCode ? ' | ' + ai.shortCode : '');
                dj.longCode = (dj.longCode ? dj.longCode : '') + (ai.longCode ? ' | ' + ai.longCode : '');
                dj.aminoAcidType = (dj.aminoAcidType ? dj.aminoAcidType : '') + (ai.aminoAcidType ? ' | ' + ai.aminoAcidType : '');
                dj.cancelDate = (dj.cancelDate ? dj.cancelDate : '') + (ai.cancelDate ? ' | ' + ai.cancelDate : '');
                dj.cancelName = (dj.cancelName ? dj.cancelName : '') + (ai.cancelName ? ' | ' + ai.cancelName : '');
                break;
              }
            }
          }
        }
        this[tableName].tableData = dest;
        this[tableName].pagerConfig.total = dest.length * 2;
        this[tableName].pagerConfig.currentPage = params.page;
        this[tableName].pagerConfig.pageSize = params.rows;
      }).finally(() => {
        this[tableName].loading = false;
      });
    },
    handleCellClick ({ row }) {
      this.$emit('callback', row);
    },
    pagerChange ({ pageSize, currentPage }) {
      const tableName = 'primerTable';
      this[tableName].pagerConfig = Object.assign(this[tableName].pagerConfig, { pageSize, currentPage });
      this.handleSearch();
    }
  }
};
</script>

<style lang="scss" scoped>
  // .mask {
  //   position: fixed;
  //   width: 100%;
  //   height: 100%;
  //   top: 0;
  //   left: 0;
  //   background: rgba(0, 0, 0, 0.1);
  //   z-index: 10;
  //   overflow: hidden;
  // }

  // .customer-name-mask {
  //   background: white;
  //   box-shadow: 2px 2px 4px gray;

  //   .top {
  //     height: 40px;
  //     line-height: 40px;
  //     margin: 0 2%;
  //     color: gray;

  //     .top-icon {
  //       font-size: 14px;
  //       cursor: pointer;
  //       margin-left: 10px;
  //       float: right;
  //     }

  //     .top-icon:hover {
  //       color: black;
  //     }
  //   }

  //   .middle-search {
  //     .ant-row {
  //       margin-left: 5px;
  //     }
  //   }
  // }
</style>
