// src/pages/peptide/components/products-mask.jsx
// 产品弹框
import {
  Button,
  Col,
  Form,
  Input,
  Row,
  Select,
  Table,
  Modal,
} from 'antd';
import React, { Component } from 'react';

import api from '@/api';
import './style.less'
import { connect } from 'dva';

const FormItem = Form.Item;
const { Option } = Select;

/**
 * 页面顶部筛选表单
 */
@Form.create()
class Search extends Component {
  constructor(props) {
    super(props);
    this.state = {
      factorys: [],
    }
  }

  componentDidMount() {
    this.submit();
    api.basic.getFactorys().then(data => {
      this.setState({
        factorys: data,
      })
    })
  }

  componentWillReceiveProps() {

  }

  submit = e => {
    if (e) e.preventDefault();
    const val = this.props.form.getFieldsValue();
    this.props.getTableData({ page: 1, ...val });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  }

  // 渲染表单
  renderForm = () => {
    const {
      form: { getFieldDecorator },
      brands,
      rangeArea,
    } = this.props;
    const { factorys } = this.state;
    return (
      <Form onSubmit={this.submit} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="编号">
              {getFieldDecorator('code')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="产品名称">
              {getFieldDecorator('desc')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="英文名称">
              {getFieldDecorator('edesc')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="旧物料号">
              {getFieldDecorator('oldCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="客户编号">
              {getFieldDecorator('customerCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="负责人编号">
              {getFieldDecorator('subcustomerCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售大区">
              {getFieldDecorator('regionCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售网点">
              {getFieldDecorator('officeCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售范围">
              {getFieldDecorator('range_area', { initialValue: '10-3110' })(
                <Select>
                    {rangeArea.map(item =>
                      <Option key={item.id} value={item.id}>{item.name}</Option>,
                    )}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="工厂">
              {getFieldDecorator('stock_factory', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                    {factorys.map(item =>
                      <Option key={item.code} value={item.code}>{`${item.code}-${item.name}`}</Option>,
                    )}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="品牌">
            {getFieldDecorator('brandCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                    {brands.map(item =>
                      <Option key={item.code} value={item.code}>{`${item.code}-${item.name}`}</Option>,
                    )}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <span className="submitButtons">
              <Button type="primary" htmlType="submit">
                查询
              </Button>
              <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
                重置
              </Button>
            </span>
          </Col>
        </Row>
      </Form>
    );
  }

  render() {
    return (
      <div className="tableListForm">{this.renderForm()}</div>
    );
  }
}

@connect(({ peptide }) => ({
  peptide,
}))
class Order extends Component {
  state = {
    formValues: {
      page: 1,
      rows: 10,
    },
    list: [],
    total: 0,
    loading: false,
    visible: false, // 遮罩层的判断
    data: [],
    dataSon: [],
    loadingSon: false,
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      visible: nextProps.visible,
    })
  }

  handleOk = () => {
    this.props.getData(this.state.data);
  };

  handleCancel = () => {
    this.props.closeMask(false)
    this.setState({
      visible: false,
    });
  };

    // 设置子值
    dataSon = v => {
      this.setState({
        loadingSon: true,
      })
      setTimeout(() => {
          this.setState({
            dataSon: v.stock.storages,
            loadingSon: false,
          })
        }, 500)
    }

  // 分页
  handleStandardTableChange = pagination => {
    this.getTableData({
      page: pagination.current,
      rows: pagination.pageSize,
    });
  }

  // 获取表格数据
  getTableData = (options = {}) => {
    const { formValues } = this.state;
    const conditions = [];
    conditions['range.channel'] = options.range_area ? options.range_area.split('-')[0] : '';
    conditions['range.organization'] = options.range_area ? options.range_area.split('-')[1] : '';
    conditions['stock.factory'] = options.stock_factory ? options.stock_factory : 3100;
    const query = Object.assign({}, formValues, options, conditions);

    this.setState({
      formValues: query,
      loading: true,
    });

    api.basic.getProductList(query).then(data => {
      this.setState({
        list: data,
        total: data.length,
        loading: false,
      });
    });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  };

  render() {
    const {
      formValues: { page: current, rows: pageSize },
      list,
      total,
      loading,
      visible,
      dataSon,
      loadingSon,
    } = this.state;
    const data = { list, pagination: { current, pageSize, total } };
    const { peptide: { commonData } } = this.props
    let tableWidth = 0;

    let columns = [
      {
        title: '编号',
        dataIndex: 'code',
        width: 150,
      },
      {
        title: '产品名称',
        dataIndex: 'desc',
        width: 300,
      },
      {
        title: '英文名称',
        dataIndex: 'edesc',
        width: 300,
      },
      {
        title: '旧物料号',
        dataIndex: 'oldCode',
        width: 150,
      },
      {
        title: '品牌',
        dataIndex: 'brand',
        width: 100,
      },
      {
        title: '包装',
        dataIndex: 'packing',
        width: 100,
      },
      {
        title: '销售单位',
        dataIndex: 'salesUnit',
        width: 200,
      },
      {
        title: '采购单位',
        dataIndex: 'purchaseUnit',
        width: 200,
      },
      {
        title: '温度条件',
        dataIndex: 'temperatureCode',
        width: 200,
        render: (text, record) => `${record.temperatureCode}-${record.temperature}`,
      },
      {
        title: '危险品标识',
        dataIndex: 'cas',
        width: 120,
      },
      {
        title: '产品价格',
        dataIndex: 'listPrice',
        width: 100,
      },
      {
        title: '客户折扣',
        dataIndex: 'custDiscount',
        width: 100,
      },
      {
        title: '客户价格',
        dataIndex: 'custPrice',
        width: 100,
      },
      {
        title: '促销价格',
        dataIndex: 'promPrice',
        width: 100,
      },
      {
        title: '库存',
        dataIndex: 'stock',
        width: 100,
        render: (text, record) => record.saleCount,
      },
      {
        title: '到货周期',
        dataIndex: 'deliPeriod',
        width: 100,
        render: (text, record) => {
          if (record.deliPeriod === 0 && record.prodPeriod === 0) {
            if (record.stock) {
              if (record.stock.saleCount > 0) {
                return '现货';
              }
            }
              return '无货';
          }
            return `预计${Math.max(record.deliPeriod, record.prodPeriod)}天到货`;
        },
      },
      {
        title: '状态',
        dataIndex: 'saleStatus',
        width: 150,
        render: text => {
          if (text === 'Z1') return '暂停销售'
          return '状态异常(促销)'
        },
      },
    ];

    const columnSon = [
        {
        title: '仓库',
        dataIndex: 'storageName',
        width: 100,
      },
      {
        title: '数量',
        dataIndex: 'saleCount',
        width: 100,
      },
    ];


    columns = columns.map(col => {
      // eslint-disable-next-line no-param-reassign
      if (!col.width) col.width = 100;
      tableWidth += col.width;
      return col
    });

    const rowSelection = {
      type: 'radio',
      onChange: (selectedRowKeys, selectedRows) => {
          this.setState({
              data: selectedRows[0],
            })
        },
    }

    return (
      <div>
        <Modal
          width="1200px"
          title="多肽氨基酸列表"
          visible={visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
            <Search getTableData={this.getTableData} brands={commonData.brands}
            rangeArea={commonData.rangeArea}/>
            <div className="tableListOperator">
            </div>

              <Table
                style={{ width: '800px', height: '100%', display: 'inline-block' }}
                bordered
                dataSource={data.list}
                columns={columns}
                scroll={{ x: tableWidth, y: 350 }}
                rowKey="code"
                rowSelection={rowSelection}
                loading={loading}
                onChange={this.handleStandardTableChange}
                onRow={record => ({ onClick: e => this.dataSon(record, e) }) }
                pagination={false}
                />

              <Table
                style={{ width: '300px', height: '100%', display: 'inline-block', marginLeft: '50px', verticalAlign: 'top' }}
                bordered
                dataSource={dataSon}
                columns={columnSon}
                scroll={{ x: 250, y: 350 }}
                rowKey="storage"
                loading={loadingSon}
                pagination={false}
                />

        </Modal>
      </div>
    );
  }
}

export default Form.create()(Order);

// src/components/peptide/products_mask.vue
<template>
  <div v-if="hackReset" class="mask">
    <div class="customer-name-mask" :style="{top: customer_name_top + 'px', left : customer_name_left + 'px', width : small ? '1100px' : '100%', height : small ? '700px' : '100%', position: small ? 'absolute' : '', borderRadius: small ? '5px' : ''}">
      <div class="top">
        <span style="float: left">产品列表</span>
        <span class="top-icon" style="padding-bottom: 10px" @click="onClose($event)"><a-icon
          type="close"/></span>
        <span class="top-icon" @click="onSmall" v-show="small"><a-icon
          type="plus-square"/></span>
        <span class="top-icon" @click="onSmall" v-show="!small"><a-icon
          type="minus-square"/></span>
      </div>
      <div class="middle-search" style="margin: 0 3%">
        <a-form layout="inline" :form="form" @submit="handleSearch">
          <div>
            <a-form-item label="编号">
              <a-input v-decorator="['code']" style="width: 193px"/>
            </a-form-item>
            <a-form-item label="产品名称">
              <a-input v-decorator="['desc']" style="width: 162px"/>
            </a-form-item>
            <a-form-item label="英文名称">
              <a-input v-decorator="['edesc']" style="width: 165px"/>
            </a-form-item>
            <a-form-item label="旧物料号">
              <a-input v-decorator="['oldCode']" style="width: 165px"/>
            </a-form-item>
            <a-form-item label="客户编号">
              <a-input v-decorator="['customerCode']" style="width: 165px"/>
            </a-form-item>
            <a-form-item label="负责人编号">
              <a-input v-decorator="['subcustomerCode']" style="width: 148px"/>
            </a-form-item>
            <a-form-item label="销售大区">
              <a-input v-decorator="['regionCode']" style="width: 165px"/>
            </a-form-item>
            <a-form-item label="销售网点">
              <a-input v-decorator="['officeCode']" style="width: 165px"/>
            </a-form-item>
            <a-form-item label="销售范围">
              <a-select v-decorator="['range_area', {initialValue : '10-3110'}]" style="width: 165px;">
                <a-select-option v-for="item in rangeArea" :key="item.id" :value="item.id">{{ item.name }}</a-select-option>
              </a-select>
            </a-form-item>
            <a-form-item label="工厂">
              <a-select v-decorator="['stock_factory', {initialValue : '3100'}]" style="width: 193px" >
                <a-select-option value="3100">3100-生工上海工厂</a-select-option>
              </a-select>
            </a-form-item>
            <a-form-item label="品牌">
              <a-select v-decorator="['brandCode', {initialValue : ''}]" style="width: 190px">
                <a-select-option value="">全部</a-select-option>
                <a-select-option v-for="item in brands" :key="item.code" :value="item.code">{{ item.code }}-{{ item.name }}</a-select-option>
              </a-select>
            </a-form-item>
          </div>
          <div>
            <a-button icon="search" @click="showData">查询</a-button>
            <a-button @click="sub" style="float:right">确定</a-button>
          </div>
        </a-form>

      </div>
      <div style="height:100%;position: relative;">
        <a-table
          ref="table"
          style="width:78%;"
          bordered
          rowKey="id"
          size="small"
          :scroll="{ x: 1900, y: 400}"
          :columns="columns"
          :dataSource="dataSource"
          :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
        >
        </a-table>
        <div style="width:20%;position: absolute; left:79%; top:0">
          <h4>库存</h4>
          <a-table
            :columns="columnSon"
            :dataSource="dataSon"
            bordered
            rowKey="id"
            ref="table1"
            size="small"
            :scroll="{ x: 200, y: 400}"/>
        </div>
      </div>

    </div>
  </div>

</template>

<script>

export default {
  name: 'CustomerMask',
  data () {
    // var self = this;
    return {
      form: this.$form.createForm(this),
      small: true,
      customer_name_top: 0,
      customer_name_left: 0,
      rangeOrganization: [],
      rangeChannel: [],
      hackReset: true,
      status: false,
      data: false,
      rangeArea: [],
      brands: [],
      columnSon: [
        { title: '仓库', dataIndex: 'storageName', width: '120px' },
        { title: '数量', dataIndex: 'saleCount', width: '80px' }
      ],
      dataSon: [],
      columns: [
        { title: '编号', dataIndex: 'code', width: '120px' },
        { title: '产品名称', dataIndex: 'desc', width: '200px' },
        { title: '英文名称', dataIndex: 'edesc', width: '200px' },
        { title: '旧物料号', dataIndex: 'oldCode', width: '120px' },
        { title: '品牌', dataIndex: 'brand', width: '80px' },
        { title: '包装', dataIndex: 'packing', width: '80px' },
        {
          title: '温度条件',
          dataIndex: 'temperatureCode',
          width: '160px',
          customRender: function (value, record, index) {
            if (value) {
              return `${record.temperatureCode}-${record.temperature}`;
            }
          }
        },
        {
          title: '危险品标识',
          dataIndex: 'cas',
          width: '120px',
          customRender: function (value) {
            return value ? value.w7_nam : '';
          }
        },
        { title: '产品价格', dataIndex: 'listPrice', align: 'right', width: '100px' },
        { title: '客户折扣', dataIndex: 'custDiscount', align: 'right', width: '100px' },
        { title: '客户价格', dataIndex: 'custPrice', align: 'right', width: '100px' },
        { title: '促销价格', dataIndex: 'promPrice', align: 'right', width: '100px' },
        {
          title: '库存',
          dataIndex: 'stock',
          width: '100px',
          align: 'right',
          customRender: function (value) {
            return value.saleCount;
          }
        },
        {
          title: '到货周期',
          dataIndex: 'deliPeriod',
          width: '100px',
          customRender: function (value, record, index) {
            if (record.deliPeriod === 0 && record.prodPeriod === 0) {
              if (record.stock.saleCount > 0) {
                return '现货';
              } else {
                return '无货';
              }
            } else {
              return '预计' + Math.max(record.deliPeriod, record.prodPeriod) + '天到货';
            }
          }
        },
        {
          title: '状态',
          dataIndex: 'saleStatus',
          width: '100px',
          customRender: function (value) {
            switch (value) {
              case 'Z1':
                return '暂停销售';
              case 'GE':
                return '状态异常(促销)';
            }
          }
        }
      ],
      queryParam: {},
      dataSource: [],
      selectedRowKeys: [],
      selectedRows: []
    };
  },
  mounted () {
    this.handleSearch();
    this.selectedRows = [];
    this.selectedRowKeys = [];
    this.rangeArea = this.$store.state.peptide.rangeArea;
    this.brands = this.$store.state.basic.brands;
    var width = document.body.clientWidth;
    var height = document.body.clientHeight;
    if (width > 1000) {
      this.customer_name_left = (width - 1100) / 2;
    }
    if (height > 600) {
      this.customer_name_top = (height - 700) / 2;
    }
  },
  watch: {
    status: function () {
      if (this.status) {
        this.hackReset = false;
        this.$nextTick(() => {
          this.hackReset = true;
        });
        this.status = false;
        this.small = true;
        this.data = false;
      }
    }
  },
  methods: {
    handleSearch () {
      const queryParam = this.form.getFieldsValue();
      if (!this.queryParam.range_area) {
        this.queryParam.range_area = '10-3110';
      }
      queryParam['range.channel'] = this.queryParam.range_area.split('-')[0] ? this.queryParam.range_area.split('-')[0] : '';
      queryParam['range.organization'] = this.queryParam.range_area.split('-')[1] ? this.queryParam.range_area.split('-')[1] : '';
      queryParam['stock.factory'] = '3100';
      const params = Object.assign({ page: 1, rows: 10 }, queryParam);
      this.$api.peptide.getProductList(params).then((data) => {
        if (this.data) {
          this.dataSource = data;
        }
      }).finally(() => {
        this.loading = false;
      });
    },
    sub () {
      if (this.selectedRows[0].saleStatus === 'Z1') {
        this.$notification.error({
          message: '错误',
          description: `不能选择暂停销售产品`
        });
        return false;
      }
      if (this.selectedRows[0]) {
        this.$emit('customerData', this.selectedRows);
        this.$emit('Closed');
        this.selectedRows = [];
        this.selectedRowKeys = [];
      } else {
        this.$notification.error({
          message: '错误',
          description: `请选择一条数据`
        });
      }
    },
    onClose (e) {
      this.$emit('Closed');
      this.status = true;
      this.selectedRows = [];
      this.selectedRowKeys = [];
      this.dataSon = [];
    },
    onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys.slice(-1);
      if (selectedRows.length === 1) {
        this.selectedRows = selectedRows;
      } else {
        for (let i = 0; i < selectedRows.length; i++) {
          if (selectedRows[i].id === this.selectedRowKeys[0]) {
            this.selectedRows = [];
            this.selectedRows[0] = selectedRows[i];
          }
        }
      }

      if (this.selectedRows) {
        for (let i = 0; i < this.selectedRows[0].stock.storages.length; i++) {
          this.selectedRows[0].stock.storages[i]['id'] = i + 1;
        }
        this.dataSon = this.selectedRows[0].stock.storages;
      } else {
        this.dataSon = [];
      }
    },
    onSmall () {
      this.small = !this.small;
    },
    onChange (dates, dateStrings) {
      this.createDateBegin = dateStrings[0];
      this.createDateEnd = dateStrings[1];
    },
    showData () {
      this.data = true;
      this.handleSearch();
    }
  }
};
</script>

<style lang="scss" scoped>
  .mask {
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: rgba(0, 0, 0, 0.1);
    z-index: 10;
    overflow: hidden;
  }

  .customer-name-mask {
    background: white;
    box-shadow: 2px 2px 4px gray;

    .top {
      height: 40px;
      line-height: 40px;
      margin: 0 2%;
      color: gray;

      .top-icon {
        font-size: 14px;
        cursor: pointer;
        margin-left: 10px;
        float: right;
      }

      .top-icon:hover {
        color: black;
      }
    }

    .middle-search {
      .ant-row {
        margin-left: 5px;
      }
    }
  }
</style>
