// src/pages/peptide/components/subCustomer-mask.jsx
// 负责人弹框
import {
  Button,
  Col,
  Form,
  Input,
  Row,
  Select,
  Table,
  Modal,
} from 'antd';
import React, { Component } from 'react';

import api from '@/api';
import './style.less'
import { connect } from 'dva';

const FormItem = Form.Item;
const { Option } = Select;

/**
 * 页面顶部筛选表单
 */
@Form.create()
class Search extends Component {
  componentDidMount() {
    this.submit();
  }

  submit = e => {
    if (e) e.preventDefault();
    const val = this.props.form.getFieldsValue();
    this.props.getTableData({ page: 1, ...val });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  }

  // 渲染表单
  renderForm = () => {
    const {
      form: { getFieldDecorator },
      regions,
      offices,
      payMethods,
      payTerms,
      rangeArea,
      currencys,
    } = this.props;
    return (
      <Form onSubmit={this.submit} layout="inline">
        <Row gutter={{ lg: 24, md: 12, sm: 6 }}>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="编号">
              {getFieldDecorator('code')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="名称">
              {getFieldDecorator('name')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="电话">
              {getFieldDecorator('telNo')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="手机">
              {getFieldDecorator('mobNo')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="邮箱">
              {getFieldDecorator('email')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="客户编号">
              {getFieldDecorator('customerCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="客户名称">
              {getFieldDecorator('customerName')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="大区">
              {getFieldDecorator('regionCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {regions.map(item => <Option key={item.code} value={item.code}>
                    {`${item.code}-${item.name}`}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="网点">
              {getFieldDecorator('officeCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {offices.map(item => <Option key={item.code} value={item.code}>
                    {`${item.code}-${item.name}`}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="币种">
              {getFieldDecorator('currency', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {currencys.map(item => <Option key={item.code} value={item.code}>
                    {`${item.code}-${item.name}`}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="付款方式">
              {getFieldDecorator('payMethodCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {payMethods.map(item => <Option key={item.code} value={item.code}>
                    {`${item.code}-${item.name}`}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="付款条件">
              {getFieldDecorator('payTermsCode', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {payTerms.map(item => <Option key={item.code} value={item.code}>
                    {`${item.code}-${item.name}`}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售员编号">
              {getFieldDecorator('salerCode')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售员名称">
              {getFieldDecorator('salerName')(<Input />)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <FormItem label="销售范围">
              {getFieldDecorator('rangeOrganization', { initialValue: '' })(
                <Select>
                  <Option value="">全部</Option>
                  {rangeArea.map(item => <Option key={item.id} value={item.id}>
                    {item.name}
                  </Option>)}
                </Select>)}
            </FormItem>
          </Col>
          <Col lg={6} md={8} sm={12}>
            <span className="submitButtons">
              <Button type="primary" htmlType="submit">
                查询
              </Button>
              <Button style={{ marginLeft: 8 }} onClick={this.handleFormReset}>
                重置
              </Button>
            </span>
          </Col>
        </Row>
      </Form>
    );
  }

  render() {
    return (
      <div className="tableListForm">{this.renderForm()}</div>
    );
  }
}

@connect(({ peptide }) => ({
  peptide,
}))
class SubCustomer extends Component {
  state = {
    formValues: {
      page: 1,
      rows: 10,
    },
    list: [],
    total: 0,
    loading: false,
    visible: false, // 遮罩层的判断
    data: [],
    modificationType: [],
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      visible: nextProps.visible,
    })
  }

  handleOk = () => {
    this.props.getData(this.state.data);
  };

  handleCancel = () => {
    this.props.closeMask(false);
    this.setState({
      visible: false,
    });
  };

  // 分页
  handleStandardTableChange = pagination => {
    this.getTableData({
      page: pagination.current,
      rows: pagination.pageSize,
    });
  }

  // 获取表格数据
  getTableData = (options = {}) => {
    const { formValues } = this.state;
    const query = Object.assign({}, formValues, options);

    this.setState({
      formValues: query,
      loading: true,
    });

    api.peptideBase.getModifications(query).then(res => {
      this.setState({
        list: res.rows,
        total: res.total,
        loading: false,
      });
    });
  }

  handleFormReset = () => {
    this.props.form.resetFields();
  };

  render() {
    const {
      formValues: { page: current, rows: pageSize },
      list,
      total,
      loading,
      visible,
      modificationType,
    } = this.state;
    const data = { list, pagination: { current, pageSize, total } };
    const { peptide: { commonData }, regions,
    offices, payMethods, payTerms, currencys } = this.props
    let tableWidth = 0;

    let columns = [
      {
        title: '编号',
        dataIndex: 'code',
        width: 100,
      },
      {
        title: '名称',
        dataIndex: 'name',
        width: 350,
      },
      {
        title: '电话',
        dataIndex: 'telNo',
        width: 100,
      },
      {
        title: '手机',
        dataIndex: 'mobNo',
        width: 100,
      },
      {
        title: '邮箱',
        dataIndex: 'email',
        width: 100,
      },
      {
        title: '客户编号',
        dataIndex: 'customerCode',
        width: 100,
      },
      {
        title: '客户名称',
        dataIndex: 'customerName',
        width: 100,
      },
      {
        title: '客户分类',
        dataIndex: 'custType',
        width: 100,
      },
      {
        title: '大区',
        dataIndex: 'regionCode',
        width: 100,
      },
      {
        title: '网点',
        dataIndex: 'officeCode',
        width: 100,
      },
      {
        title: '币种',
        dataIndex: 'currency',
        width: 100,
      },
      {
        title: '付款方式',
        dataIndex: 'payMethodCode',
        width: 100,
      },
      {
        title: '付款条件',
        dataIndex: 'payTermsCode',
        width: 100,
      },
      {
        title: '销售员',
        dataIndex: 'salerCode',
        width: 100,
      },
      {
        title: '销售员名称',
        dataIndex: 'salerName',
        width: 120,
      },
      {
        title: '增值税号',
        dataIndex: 'vatCode',
        width: 100,
      },
      {
        title: '信用额度',
        dataIndex: 'credit',
        width: 100,
      },
      {
        title: '余额',
        dataIndex: 'balance',
        width: 100,
      },
      {
        title: '销售冻结(当前渠道)',
        dataIndex: 'customerRangeFrozen',
        width: 200,
      },
      {
        title: '销售冻结(所有渠道)',
        dataIndex: 'customerFrozen',
        width: 200,
      },
    ];

    columns = columns.map(col => {
      // eslint-disable-next-line no-param-reassign
      if (!col.width) col.width = 100;
      tableWidth += col.width;
      return col
    });

    const rowSelection = {
      type: 'radio',
      onChange: (selectedRowKeys, selectedRows) => {
          this.setState({
              data: selectedRows[0],
            })
        },
    }

    return (
      <div>
        <Modal
          width="1200px"
          title="负责人列表"
          visible={visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
        >
            <Search
              getTableData={this.getTableData}
              status={commonData.status}
              modificationType={modificationType}
              regions={regions}
              offices={offices}
              payMethods={payMethods}
              payTerms={payTerms}
              rangeArea={commonData.rangeArea}
              currencys={currencys}
             />
            <div className="tableListOperator">
            </div>
            <Table
              dataSource={data.list}
              columns={columns}
              scroll={{ x: tableWidth, y: 300 }}
              pagination={data.pagination}
              rowKey="code"
              rowSelection={rowSelection}
              loading={loading}
              onChange={this.handleStandardTableChange}
              />
        </Modal>
      </div>
    );
  }
}

export default Form.create()(SubCustomer);

// src/components/peptide/sub_customer_mask.vue
<template>
  <div>
    <a-form layout="inline" :form="form" @submit="handleSearch">
      <div>
        <a-form-item label="编号">
          <a-input v-decorator="['code']" title="" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="名称">
          <a-input v-decorator="['customerName']" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="电话">
          <a-input v-decorator="['charge_person']" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="手机">
          <a-input v-decorator="['order']" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="邮箱">
          <a-input v-decorator="['saler']" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="客户编号">
          <a-input v-decorator="['saler']" style="width: 163px"/>
        </a-form-item>
        <a-form-item label="客户名称">
          <a-input v-decorator="['saler']" style="width: 163px"/>
        </a-form-item>
        <a-form-item label="大区">
          <a-select v-decorator="['currency_type']" style="width: 190px;">
            <a-select-option value="0">全部</a-select-option>
            <a-select-option value="1">关闭</a-select-option>
            <a-select-option value="2">运行中</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="网点">
          <a-select v-decorator="['commercial_network']" style="width: 190px">
            <a-select-option value="0">全部</a-select-option>
            <a-select-option value="1">关闭</a-select-option>
            <a-select-option value="2">运行中</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="币种">
          <a-input v-decorator="['saler']" style="width: 190px"/>
        </a-form-item>
        <a-form-item label="付款方式">
          <a-select v-decorator="['sales_region']" style="width: 165px">
            <a-select-option value="0">全部</a-select-option>
            <a-select-option value="1">关闭</a-select-option>
            <a-select-option value="2">运行中</a-select-option>
          </a-select>
        </a-form-item>

        <a-form-item label="付款条件">
          <a-select v-decorator="['sales_organization']" style="width: 163px">
            <a-select-option value="0">全部</a-select-option>
            <a-select-option value="1">关闭</a-select-option>
            <a-select-option value="2">运行中</a-select-option>
          </a-select>
        </a-form-item>

        <a-form-item label="销售员编号">
          <a-input v-decorator="['saler']" style="width: 148px"/>
        </a-form-item>

        <a-form-item label="销售员名称">
          <a-input v-decorator="['saler']" style="width: 148px"/>
        </a-form-item>

        <a-form-item label="销售范围">
          <a-select v-decorator="['distribution_channel']" style="width: 165px">
            <a-select-option value="0">全部</a-select-option>
            <a-select-option value="1">关闭</a-select-option>
            <a-select-option value="2">运行中</a-select-option>
          </a-select>
        </a-form-item>
      </div>
      <div style="margin-bottom:10px">
        <a-button type="primary" icon="search" @click="showData">查询</a-button>
      </div>
    </a-form>

    <vxe-grid
      highlight-hover-row
      auto-resize
      :ref="subCustomerMask.ref"
      :columns="subCustomerMask.columns"
      :data.sync="subCustomerMask.tableData"
      :loading="subCustomerMask.loading"
      :edit-rules="subCustomerMask.editRules"
      :edit-config="{key: 'id', trigger: 'dblclick', mode: 'row', showIcon: false, autoClear: false}"
      :pager-config="subCustomerMask.pagerConfig"
      @cell-dblclick="(options) => handleCellDblclick(options)"
      @page-change="pagerChange">
      >
    </vxe-grid>
  </div>

</template>

<script>
const tableName = 'subCustomerMask';

export default {
  name: 'PeptideSubCustomerMask',
  data () {
    return {
      form: this.$form.createForm(this),
      subCustomerMask: {
        id: 0,
        ref: 'subCustomerMask',
        xTable: null,
        editIndex: -1,
        loading: false,
        tableData: [],
        columns: [],
        pagerConfig: {
          currentPage: 1,
          pageSize: 10,
          total: 0
        }
      },
      small: true,
      rangeOrganization: [],
      rangeChannel: [],
      hackReset: true,
      status: false,
      data: false
    };
  },
  mounted () {
    this.setColumns();
    this.handleSearch();
  },
  watch: {
    status: function () {
      if (this.status) {
        this.hackReset = false;
        this.$nextTick(() => {
          this.hackReset = true;
        });
        this.status = false;
        this.small = true;
        this.data = false;
      }
    }
  },
  methods: {
    setColumns () {
      const columns = [
        { type: 'index', width: 40 },
        { title: '编号', field: 'code' },
        { title: '公司', field: 'name' },
        { title: '电话', field: 'telNo' },
        { title: '手机', field: 'mobNo' },
        { title: '邮箱', field: 'email' },
        { title: '分类', field: 'type' },
        { title: '大区', field: 'regionCode' },
        { title: '网点', field: 'officeCode' },
        { title: '币种', field: 'currency' },
        { title: '付款方式', field: 'payMethodCode' },
        { title: '付款条件', field: 'payTermsCode' },
        { title: '销售员名称', field: 'salerName' },
        { title: '销售冻结(当前渠道)', field: 'customerRangeFrozen' },
        { title: '销售冻结(所有渠道)', field: 'customerFrozen' },
        { title: '客户性质', field: 'industryText' }
      ];
      columns.forEach(function (e) {
        if (!e.width) e.width = 130;
      });

      this[tableName].columns = columns;

      this[tableName].xTable = this.$refs[this[tableName].ref].$refs.xTable;
    },
    handleSearch (e) {
      if (e) e.preventDefault();
      this[tableName].loading = true;

      const queryParam = this.form.getFieldsValue();

      queryParam.createDateBegin = this.createDateBegin;
      queryParam.createDateEnd = this.createDateEnd;
      const params = Object.assign({ page: this[tableName].pagerConfig.currentPage, rows: this[tableName].pagerConfig.pageSize }, queryParam);
      this.$api.peptideorder.getOrder(params).then((data) => {
        this[tableName].tableData = data.rows;
        this[tableName].pagerConfig.total = data.total;
        this[tableName].pagerConfig.currentPage = params.page;
        this[tableName].pagerConfig.pageSize = params.rows;
      }).finally(() => {
        this[tableName].loading = false;
      });
    },
    pagerChange ({ pageSize, currentPage }) {
      this[tableName].pagerConfig = Object.assign(this[tableName].pagerConfig, { pageSize, currentPage });
      this.handleSearch();
    },
    onClose (row = {}) {
      this.$emit('Closed', row, 2);
      this.status = true;
    },
    handleCellDblclick ({ row }) {
      this.onClose(row);
    },
    onSelectChange (selectedRowKeys, selectedRows) {
      this.selectedRowKeys = selectedRowKeys;
      this.selectedRows = selectedRows;
    },
    onSmall () {
      this.small = !this.small;
    },
    onChange (dates, dateStrings) {
      this.createDateBegin = dateStrings[0];
      this.createDateEnd = dateStrings[1];
    },
    showData () {
      this.data = true;
      this.$refs.table.refresh(true);
    }
  }
};
</script>

<style lang="scss" scoped>
</style>
